/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.CategoriaJpaController;
import controller.ClienteJpaController;
import controller.*;
import controller.ProdutoJpaController;
import controller.exceptions.IllegalOrphanException;
import controller.exceptions.NonexistentEntityException;
import java.awt.CardLayout;
import java.util.Date;
import java.util.List;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import model.Categoria;
import model.*;
import model.Produto;
import model.modeladoresdetabela.ClienteTableModel;
import model.modeladoresdetabela.EncomendaTableModel;
import model.modeladoresdetabela.ProdutoTableModel;
import model.modeladoresdetabela.UsuarioTableModel;

/**
 *
 * @author Tembe
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setTitle("Organizador de Encomendas ");
        for (Categoria categoria : lista) {
            txtCategorias.addItem(categoria);
        }
        for (Produto p : prodJpa.findProdutoEntities()) {
            txtProdutoEnc.addItem(p);
        }
        for (Cliente c : clienteJpa.findClienteEntities()) {
            txtClienteEnc.addItem(c);
        }
        tabela.setModel(new ProdutoTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        pnNavegador = new javax.swing.JPanel();
        btnEncomendas = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnActividades = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        cartao = new javax.swing.JPanel();
        pnProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSalvarProdutos = new javax.swing.JButton();
        btnRemoverProdutos = new javax.swing.JButton();
        txtCategorias = new javax.swing.JComboBox<>();
        txtReferencia = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtVenda = new javax.swing.JTextField();
        txtCompra = new javax.swing.JTextField();
        txtAlerta = new javax.swing.JTextField();
        btnEditarProd = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        pnEncomenda = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtProdutoEnc = new javax.swing.JComboBox<>();
        txtClienteEnc = new javax.swing.JComboBox<>();
        txtEstadoEntrega = new javax.swing.JComboBox<>();
        txtTotalEnc = new javax.swing.JTextField();
        txtValorEntradaEnc = new javax.swing.JTextField();
        btnSalvarEncomenda = new javax.swing.JButton();
        btnRemoverEncomenda = new javax.swing.JButton();
        txtObservacaoEnc = new javax.swing.JTextField();
        txtHoraEntrega = new javax.swing.JTextField();
        btnAddProduto = new javax.swing.JButton();
        btnEditarEncomenda = new javax.swing.JButton();
        txtDiaEntrega = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        pnCliente = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNomeCli = new javax.swing.JTextField();
        txtUltimaEncCli = new javax.swing.JTextField();
        txtContactoPrinCli = new javax.swing.JTextField();
        txtContactoAltCli = new javax.swing.JTextField();
        txtLocalizacaoCli = new javax.swing.JTextField();
        txtEmailCli = new javax.swing.JTextField();
        txtGeneroCli = new javax.swing.JComboBox<>();
        btnSalvarCli = new javax.swing.JButton();
        btnRemoverCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtTotalComprasCli = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        btnPesquiarCliente = new javax.swing.JButton();
        txtPesquisarCliente = new javax.swing.JTextField();
        pnUsuario = new javax.swing.JPanel();
        txtGeneroUser = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txtNomeUser = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtEmailUser = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtContactoUser = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnSalvarCompra1 = new javax.swing.JButton();
        btnRemoverUsuario = new javax.swing.JButton();
        btnEditarUser = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        txtCargoUser = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        txtContactoAlternaticoUser = new javax.swing.JTextField();
        txtMoradaUser = new javax.swing.JComboBox<>();
        txtAnoContratacao = new com.toedter.calendar.JDateChooser();

        jTextField7.setText("jTextField7");

        jLabel24.setText("jLabel24");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEncomendas.setText("Encomendas");
        btnEncomendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncomendasActionPerformed(evt);
            }
        });

        btnProdutos.setText("Produtos");
        btnProdutos.setSelected(true);
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnCategorias.setText("Categorias");
        btnCategorias.setEnabled(false);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });

        btnActividades.setText("Actividades");
        btnActividades.setEnabled(false);
        btnActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadesActionPerformed(evt);
            }
        });

        btnUsuarios.setText("Usuários");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNavegadorLayout = new javax.swing.GroupLayout(pnNavegador);
        pnNavegador.setLayout(pnNavegadorLayout);
        pnNavegadorLayout.setHorizontalGroup(
            pnNavegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNavegadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNavegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEncomendas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnNavegadorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnActividades, btnCategorias, btnClientes, btnEncomendas, btnProdutos, btnUsuarios});

        pnNavegadorLayout.setVerticalGroup(
            pnNavegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNavegadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEncomendas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pnNavegadorLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnActividades, btnCategorias, btnClientes, btnEncomendas, btnProdutos, btnUsuarios});

        getContentPane().add(pnNavegador, java.awt.BorderLayout.LINE_START);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.setSelectionBackground(new java.awt.Color(0, 153, 204));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        cartao.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Categoria");

        jLabel2.setText("Preço Compra  ou custo de Produção");

        jLabel3.setText("Referência");

        jLabel4.setText("Descrição");

        jLabel5.setText("Preço Venda");

        jLabel6.setText("Quantidade");

        jLabel7.setText("Quantidade de alerta ");

        btnSalvarProdutos.setText("Salvar");
        btnSalvarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdutosActionPerformed(evt);
            }
        });

        btnRemoverProdutos.setText("Remover");
        btnRemoverProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverProdutosActionPerformed(evt);
            }
        });

        txtCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriasActionPerformed(evt);
            }
        });

        txtVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendaActionPerformed(evt);
            }
        });

        btnEditarProd.setText("Editar");
        btnEditarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Registo de Produtos");

        javax.swing.GroupLayout pnProdutoLayout = new javax.swing.GroupLayout(pnProduto);
        pnProduto.setLayout(pnProdutoLayout);
        pnProdutoLayout.setHorizontalGroup(
            pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProdutoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(689, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnProdutoLayout.createSequentialGroup()
                        .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAlerta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtCategorias, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnProdutoLayout.createSequentialGroup()
                                .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnProdutoLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtReferencia)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(txtVenda))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnProdutoLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addGap(129, 129, 129))
                                    .addComponent(txtDescricao)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQuantidade)))
                            .addGroup(pnProdutoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalvarProdutos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoverProdutos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarProd)))))
                .addGap(32, 32, 32))
        );

        pnProdutoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditarProd, btnRemoverProdutos, btnSalvarProdutos});

        pnProdutoLayout.setVerticalGroup(
            pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProdutoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarProdutos)
                    .addComponent(btnRemoverProdutos)
                    .addComponent(btnEditarProd))
                .addContainerGap())
        );

        pnProdutoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditarProd, btnRemoverProdutos, btnSalvarProdutos});

        cartao.add(pnProduto, "cardProd");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Dia de Entrega");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Produto");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Cliente");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Hora de Entrega");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Estado de Entrega");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Observação");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Total a Pagar");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Valor de Entrada");

        txtProdutoEnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProdutoEncMouseClicked(evt);
            }
        });
        txtProdutoEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoEncActionPerformed(evt);
            }
        });

        txtClienteEnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClienteEncMouseClicked(evt);
            }
        });

        txtEstadoEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entregue", "Por Entregar", "Cancelado" }));

        btnSalvarEncomenda.setText("Salvar");
        btnSalvarEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEncomendaActionPerformed(evt);
            }
        });

        btnRemoverEncomenda.setText("Remover");
        btnRemoverEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverEncomendaActionPerformed(evt);
            }
        });

        txtHoraEntrega.setEditable(false);
        txtHoraEntrega.setBackground(new java.awt.Color(153, 153, 153));

        btnAddProduto.setText("Add");

        btnEditarEncomenda.setText("Actualizar");
        btnEditarEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEncomendaActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Registo de Encomendas");

        javax.swing.GroupLayout pnEncomendaLayout = new javax.swing.GroupLayout(pnEncomenda);
        pnEncomenda.setLayout(pnEncomendaLayout);
        pnEncomendaLayout.setHorizontalGroup(
            pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEncomendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEncomendaLayout.createSequentialGroup()
                        .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdutoEnc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtClienteEnc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnEncomendaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(btnAddProduto))
                            .addComponent(txtDiaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoraEntrega)
                            .addComponent(txtObservacaoEnc)
                            .addComponent(txtEstadoEntrega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnEncomendaLayout.createSequentialGroup()
                                .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(136, 136, 136)))
                        .addGap(28, 28, 28)
                        .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnEncomendaLayout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addComponent(btnSalvarEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoverEncomenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarEncomenda))
                            .addGroup(pnEncomendaLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addGap(167, 167, 167))
                            .addComponent(txtValorEntradaEnc)
                            .addComponent(txtTotalEnc)
                            .addGroup(pnEncomendaLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(185, 185, 185)))
                        .addGap(25, 25, 25))
                    .addGroup(pnEncomendaLayout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pnEncomendaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditarEncomenda, btnRemoverEncomenda, btnSalvarEncomenda});

        pnEncomendaLayout.setVerticalGroup(
            pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEncomendaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(7, 7, 7)
                .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotalEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDiaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdutoEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorEntradaEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddProduto)
                        .addComponent(jLabel13))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObservacaoEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarEncomenda)
                    .addComponent(btnRemoverEncomenda)
                    .addComponent(btnEditarEncomenda))
                .addContainerGap())
        );

        cartao.add(pnEncomenda, "cardEnc");

        jLabel16.setText("Nome");

        jLabel17.setText("E-mail");

        jLabel18.setText("Última Encomenda");

        jLabel19.setText("Localização");

        jLabel20.setText("Contacto Principal");

        jLabel21.setText("Contacto Alternativo");

        jLabel22.setText("Género");

        txtUltimaEncCli.setEditable(false);

        txtGeneroCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        btnSalvarCli.setText("Salvar");
        btnSalvarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCliActionPerformed(evt);
            }
        });

        btnRemoverCliente.setText("Remover");
        btnRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverClienteActionPerformed(evt);
            }
        });

        btnEditarCliente.setText("Actualizar");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        jLabel23.setText("Total Compras Feitas ");

        txtTotalComprasCli.setEditable(false);

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Registo de Clientes");

        btnPesquiarCliente.setText("Pesquisar");
        btnPesquiarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquiarClienteActionPerformed(evt);
            }
        });

        txtPesquisarCliente.setText("Pesquisar");
        txtPesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarClienteMouseClicked(evt);
            }
        });
        txtPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnClienteLayout = new javax.swing.GroupLayout(pnCliente);
        pnCliente.setLayout(pnClienteLayout);
        pnClienteLayout.setHorizontalGroup(
            pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPesquisarCliente)
                            .addComponent(btnPesquiarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCli)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(txtEmailCli)
                            .addComponent(jLabel22)
                            .addComponent(txtGeneroCli, 0, 270, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnClienteLayout.createSequentialGroup()
                                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUltimaEncCli)
                                    .addComponent(txtLocalizacaoCli)
                                    .addGroup(pnClienteLayout.createSequentialGroup()
                                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(txtTotalComprasCli, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 106, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnClienteLayout.createSequentialGroup()
                                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtContactoPrinCli)
                                            .addComponent(jLabel21)
                                            .addComponent(txtContactoAltCli))
                                        .addGap(105, 105, 105))
                                    .addGroup(pnClienteLayout.createSequentialGroup()
                                        .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnClienteLayout.createSequentialGroup()
                                                .addComponent(btnSalvarCli)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnRemoverCliente)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnEditarCliente))
                                            .addComponent(jLabel20))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(pnClienteLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        pnClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRemoverCliente, btnSalvarCli});

        pnClienteLayout.setVerticalGroup(
            pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnClienteLayout.createSequentialGroup()
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquiarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUltimaEncCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactoPrinCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContactoAltCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalizacaoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarCli)
                    .addComponent(btnRemoverCliente)
                    .addComponent(btnEditarCliente)
                    .addComponent(txtTotalComprasCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cartao.add(pnCliente, "cardCliente");

        txtGeneroUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        jLabel25.setText("Nome");

        jLabel27.setText("E-mail");

        jLabel28.setText("Género");

        jLabel29.setText("Ano Contração");

        jLabel30.setText("Localização");

        jLabel31.setText("Cargo");

        jLabel33.setText("Contacto Principal");

        btnSalvarCompra1.setText("Salvar");
        btnSalvarCompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCompra1ActionPerformed(evt);
            }
        });

        btnRemoverUsuario.setText("Remover");
        btnRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUsuarioActionPerformed(evt);
            }
        });

        btnEditarUser.setText("Actualizar");
        btnEditarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUserActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Registo de Usuários");

        txtCargoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Administrador", "Super-User" }));
        txtCargoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoUserActionPerformed(evt);
            }
        });

        jLabel26.setText("Contacto Alternativo");

        txtMoradaUser.setEditable(true);
        txtMoradaUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marracuene", "Matola", "Matutíne", "Moamba", "Xinavane", "Manhiça", "Magude", "C. Maputo", "Namaacha", "Boane", "Gaza", "Inhambane", "Manica", "Sofala", "Tete", "Zambézia", "Nampula", "Niassa", "Cabo-Delgado" }));

        javax.swing.GroupLayout pnUsuarioLayout = new javax.swing.GroupLayout(pnUsuario);
        pnUsuario.setLayout(pnUsuarioLayout);
        pnUsuarioLayout.setHorizontalGroup(
            pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnUsuarioLayout.createSequentialGroup()
                        .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmailUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGeneroUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnUsuarioLayout.createSequentialGroup()
                                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCargoUser, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMoradaUser, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAnoContratacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnUsuarioLayout.createSequentialGroup()
                                        .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtContactoAlternaticoUser)
                                            .addComponent(txtContactoUser))
                                        .addGap(88, 88, 88))
                                    .addGroup(pnUsuarioLayout.createSequentialGroup()
                                        .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnUsuarioLayout.createSequentialGroup()
                                                .addComponent(btnSalvarCompra1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnRemoverUsuario)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnEditarUser))
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel33))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(pnUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        pnUsuarioLayout.setVerticalGroup(
            pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUsuarioLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtContactoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAnoContratacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel30)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactoAlternaticoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMoradaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarCompra1)
                    .addComponent(btnRemoverUsuario)
                    .addComponent(btnEditarUser)
                    .addComponent(txtCargoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        cartao.add(pnUsuario, "cardUser");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(cartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) cartao.getLayout();
        c.show(cartao, "cardProd");
        tabela.setModel(new ProdutoTableModel());
        
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void txtVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendaActionPerformed

    private void btnEditarEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEncomendaActionPerformed
        // TODO add your handling code here:
        
        
        
        try {
            
            enc.setTotalPorPagar(Double.parseDouble(txtTotalEnc.getText()));
            Cliente c = (Cliente) txtClienteEnc.getSelectedItem();
            enc.setClienteId(c);
            Produto p = (Produto) txtProdutoEnc.getSelectedItem();
            enc.setProdutoid(p);
            enc.setTotalPorPagar(Double.parseDouble(txtTotalEnc.getText()));
            enc.setDiaMarcacao(new Date());
            enc.setEntregaDia(txtDiaEntrega.getDate());
            enc.setEstadoEntrega((String) txtEstadoEntrega.getSelectedItem());
            enc.setHoraEntrega(null);
            enc.setValorEntrada(Double.parseDouble(txtValorEntradaEnc.getText()));
            Usuario u = userJpa.findUsuario(2);
            enc.setUsuarioId(u);
        
            encJpa.edit(enc);
            tabela.setModel(new EncomendaTableModel());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEditarEncomendaActionPerformed

    private void txtCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriasActionPerformed

    private void btnSalvarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdutosActionPerformed
         // TODO add your handling code here:
        Produto prod = new Produto();
        
        try {
            // pegando o id da categoria selecionada
            Categoria categ = (Categoria) txtCategorias.getSelectedItem();
            prod.setCategoria(categ.getId());
            prod.setAlerta(Integer.parseInt(txtAlerta.getText()));
            prod.setDescricao(txtDescricao.getText());
            prod.setReferencia(txtReferencia.getText());
            prod.setPrecoCompra(Double.parseDouble(txtCompra.getText()));
            prod.setPrecoVenda(Double.parseDouble(txtVenda.getText()));
            prod.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            
            // pegando a data em que ee feita a ultima alteracao
            Date dia = new Date();
            prod.setUltimoAbastecimento(dia);
            
            // salvando os dados na base de dados
            prodJpa.create(prod);
            
            limparCampos();
            
            // criar aqui uma forma de actualizar a tabela de produtos sempre que se efectua um novo registo
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro, \n  retifique digitando correctamente os dados");
        }
    }//GEN-LAST:event_btnSalvarProdutosActionPerformed

    private void btnEncomendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncomendasActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) cartao.getLayout();
        c.show(cartao, "cardEnc");
        tabela.setModel(new EncomendaTableModel());
        
    }//GEN-LAST:event_btnEncomendasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) cartao.getLayout();
        c.show(cartao, "cardCliente");
        tabela.setModel(new ClienteTableModel());
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) cartao.getLayout();
        c.show(cartao, "cardCateg");
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadesActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) cartao.getLayout();
        c.show(cartao, "cardCateg");
    }//GEN-LAST:event_btnActividadesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout) cartao.getLayout();
        c.show(cartao, "cardUser");
        tabela.setModel(new UsuarioTableModel());
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnSalvarEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEncomendaActionPerformed
        // TODO add your handling code here:
        Encomenda e = new Encomenda();
        
        try {
            
            e.setTotalPorPagar(Double.parseDouble(txtTotalEnc.getText()));
            Cliente c = (Cliente) txtClienteEnc.getSelectedItem();
            e.setClienteId(c);
            Produto p = (Produto) txtProdutoEnc.getSelectedItem();
            e.setProdutoid(p);
            e.setTotalPorPagar(Double.parseDouble(txtTotalEnc.getText()));
            e.setDiaMarcacao(new Date());
            e.setEntregaDia(txtDiaEntrega.getDate());
            e.setEstadoEntrega((String) txtEstadoEntrega.getSelectedItem());
            e.setHoraEntrega(null);
            e.setValorEntrada(1324.4);
            
            // ao fazer login, o usuario activo passa para as operacoes
            Usuario u = userJpa.findUsuario(2);
            e.setUsuarioId(u);
            
            encJpa.create(e);
            tabela.setModel(new EncomendaTableModel());
            limparCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Formato não suportado! \n"+ex);
        }
        
        
    }//GEN-LAST:event_btnSalvarEncomendaActionPerformed

    private void txtPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarClienteActionPerformed

    private void txtPesquisarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarClienteMouseClicked
        // TODO add your handling code here:
        txtPesquisarCliente.setText("");
    }//GEN-LAST:event_txtPesquisarClienteMouseClicked

    private void btnSalvarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCliActionPerformed
        // TODO add your handling code here:
        Cliente cli = new Cliente();
        try {
            cli.setNome(txtNomeCli.getText());
            cli.setEmail(txtEmailCli.getText());
            cli.setGenero((String) txtGeneroCli.getSelectedItem());
            cli.setLocalizacao(txtLocalizacaoCli.getText()); 
            cli.setUltimaCompra(new Date());
            cli.setContactoAlternativo(txtContactoAltCli.getText());
            cli.setContactoPrincipal(txtContactoPrinCli.getText());
            
            clienteJpa.create(cli);
            tabela.setModel(new ClienteTableModel());
            limparCampos();
            System.out.println("Cliente Registado com sucesso... ");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSalvarCliActionPerformed

    private void btnRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverClienteActionPerformed
        // TODO add your handling code here:
        try {
            
            clienteJpa.destroy(cliente.getId());
            tabela.setModel(new ClienteTableModel());
            limparCampos();
            System.out.println("Cliente Registado com sucesso... ");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRemoverClienteActionPerformed

    private void txtClienteEncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClienteEncMouseClicked
        // TODO add your handling code here:
        txtClienteEnc.removeAllItems();
        for (Cliente c : clienteJpa.findClienteEntities()) {
            txtClienteEnc.addItem(c);
        }
    }//GEN-LAST:event_txtClienteEncMouseClicked

    private void txtProdutoEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoEncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoEncActionPerformed

    private void txtProdutoEncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProdutoEncMouseClicked
         // TODO add your handling code here:
        txtProdutoEnc.removeAllItems();
        for (Produto p : prodJpa.findProdutoEntities()) {
            txtProdutoEnc.addItem(p);
        }
    }//GEN-LAST:event_txtProdutoEncMouseClicked

    private void btnPesquiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquiarClienteActionPerformed
        // TODO add your handling code here:
        txtPesquisarCliente.getText();
         Cliente  clientePesq = clienteJpa.findCliente(Integer.parseInt(txtPesquisarCliente.getText()));
         System.out.println("Cliene=te: "+ clientePesq.toString());
         
         
    }//GEN-LAST:event_btnPesquiarClienteActionPerformed

    private void txtCargoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoUserActionPerformed

    private void btnRemoverProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverProdutosActionPerformed
        // TODO add your handling code here:
        try {
            prodJpa.destroy(p.getId());
            tabela.setModel(new ProdutoTableModel());
        } catch (IllegalOrphanException | NonexistentEntityException e) {
            JOptionPane.showMessageDialog(null, "Erro ao apagar  dados... "+e, "Erro", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btnRemoverProdutosActionPerformed

    /**
     * Especifica que o modelo assumido pela tabele e retorna os elementos consoante isso ja
     * que uso a mesma tabela para todos os elementos
     * @param evt 
     */
    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (tabela.getModel() instanceof ProdutoTableModel) {
            // Passando os valores para os campos de edicao
            p = prodJpa.findProduto(Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString()));
            // Passagem dos dados antigos aos campos de edicao
            txtReferencia.setText(p.getReferencia());
            txtCategorias.setSelectedItem(p.getCategoria().toString());
            txtAlerta.setText(p.getAlerta().toString());
            txtVenda.setText(p.getPrecoVenda().toString());
            txtCompra.setText(p.getPrecoCompra().toString());
            txtQuantidade.setText(p.getQuantidade().toString());
            txtDescricao.setText(p.getDescricao());
            System.out.println("Pressed Line: "+ tabela.getSelectedRow() + " Produtos");
            
        }else if(tabela.getModel() instanceof ClienteTableModel){
            
            cliente = clienteJpa.findCliente(Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString()));
            
            try {
            txtNomeCli.setText(cliente.getNome());
            txtEmailCli.setText(cliente.getEmail());
            txtGeneroCli.setSelectedItem(cliente.getGenero());
            txtLocalizacaoCli.setText(cliente.getLocalizacao()); 
            txtContactoAltCli.setText(cliente.getContactoAlternativo());
            txtContactoPrinCli.setText(cliente.getContactoPrincipal());
            
            
            System.out.println("Cliente Editado com sucesso... ");
            
        } catch (Exception e) {
        }
            System.out.println("Pressed Line: "+ tabela.getSelectedRow() + " Cliente");
            
        }else if(tabela.getModel() instanceof UsuarioTableModel){
            
            user = userJpa.findUsuario(Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString()));
            
            txtAnoContratacao.setDate(user.getAnoContratacao());
            txtEmailUser.setText(user.getEmail());
            txtCargoUser.setSelectedItem(user.getCargo());
            txtNomeUser.setText(user.getNome());
            txtGeneroUser.setSelectedItem(user.getGenero());
            txtMoradaUser.setSelectedItem(user.getMorada());
            txtContactoUser.setText(user.getContacto());
            
            System.out.println("Pressed Line: "+ tabela.getSelectedRow() + " User");
        }else if(tabela.getModel() instanceof EncomendaTableModel){
            
            enc = encJpa.findEncomenda(Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString()));
            
            txtClienteEnc.setSelectedItem(enc.getClienteId());
            txtProdutoEnc.setSelectedItem(enc.getProdutoid());
            txtObservacaoEnc.setText(enc.getObservacao());
            txtDiaEntrega.setDate(enc.getEntregaDia());
            txtTotalEnc.setText(enc.getProdutoid().getPrecoCompra().toString());
            txtEstadoEntrega.setSelectedItem(enc.getEstadoEntrega());
            txtValorEntradaEnc.setText(enc.getValorEntrada().toString());
            txtClienteEnc.setSelectedItem(enc.getClienteId().toString());
            
            System.out.println("Pressed Line: "+ tabela.getSelectedRow() + " Encomenda");
              
        }else{
            System.out.println("TAbela nao especificada");
        }
    }//GEN-LAST:event_tabelaMouseClicked
    /**
     * Editar Produtos
     * @param evt 
     */
    private void btnEditarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdActionPerformed
        // TODO add your handling code here:
        
        try {
            // se a categoria tiver sido mudada, ele entra e faz as alteracoes da categoria caso contrario mantem a anterior
            if (txtCategorias.getSelectedItem()!=null) {
                Categoria categ = (Categoria) txtCategorias.getSelectedItem();
                p.setCategoria(categ.getId());
            }
            
            p.setAlerta(Integer.parseInt(txtAlerta.getText()));
            p.setDescricao(txtDescricao.getText());
            p.setReferencia(txtReferencia.getText());
            p.setPrecoCompra(Double.parseDouble(txtCompra.getText()));
            p.setPrecoVenda(Double.parseDouble(txtVenda.getText()));
            p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            
            prodJpa.edit(p);
            tabela.setModel(new ProdutoTableModel());
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Ocorreu um erro "+e, "Erro", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btnEditarProdActionPerformed
    /**
     * Remover encomenda 
     * @param evt 
     */
    private void btnRemoverEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverEncomendaActionPerformed
        // TODO add your handling code here:
        
        try {
            encJpa.destroy(enc.getId());
            tabela.setModel(new EncomendaTableModel());
            limparCampos();
        } catch (IllegalOrphanException | NonexistentEntityException e) {
            JOptionPane.showMessageDialog(null, "Erro ao apagar  dados... "+e, "Erro", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btnRemoverEncomendaActionPerformed

    private void btnSalvarCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCompra1ActionPerformed
        // TODO add your handling code here:
        Usuario u = new Usuario();
        
        try {
            
            u.setAnoContratacao(txtAnoContratacao.getDate());
            u.setEmail(txtEmailUser.getText());
            u.setCargo(txtCargoUser.getSelectedItem().toString());
            u.setNome(txtNomeUser.getText());
            u.setGenero(txtGeneroUser.getSelectedItem().toString());
            u.setMorada(txtMoradaUser.getSelectedItem().toString());
            u.setContacto(txtContactoUser.getText());
            
            userJpa.create(u);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " Ocorreu um erro ao salvar o User...\n "
                    + ""+e, "ERRO", JOptionPane.ERROR_MESSAGE, null);
        }
        
        
    }//GEN-LAST:event_btnSalvarCompra1ActionPerformed

    private void btnRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUsuarioActionPerformed
         // TODO add your handling code here:
         try {
            userJpa.destroy(user.getId());
            tabela.setModel(new UsuarioTableModel());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRemoverUsuarioActionPerformed

    private void btnEditarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUserActionPerformed
         // TODO add your handling code here:
         try {
            user.setAnoContratacao(txtAnoContratacao.getDate());
            user.setEmail(txtEmailUser.getText());
            user.setCargo(txtCargoUser.getSelectedItem().toString());
            user.setNome(txtNomeUser.getText());
            user.setGenero(txtGeneroUser.getSelectedItem().toString());
            user.setMorada(txtMoradaUser.getSelectedItem().toString());
            user.setContacto(txtContactoUser.getText());
            userJpa.edit(user);
            tabela.setModel(new UsuarioTableModel());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEditarUserActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
         
        try {
            
            cliente.setNome(txtNomeCli.getText());
            cliente.setEmail(txtEmailCli.getText());
            cliente.setGenero((String) txtGeneroCli.getSelectedItem());
            cliente.setLocalizacao(txtLocalizacaoCli.getText()); 
            cliente.setUltimaCompra(new Date());
            cliente.setContactoAlternativo(txtContactoAltCli.getText());
            cliente.setContactoPrincipal(txtContactoPrinCli.getText());
            
            clienteJpa.edit(cliente);
            tabela.setModel(new ClienteTableModel());
            limparCampos();
            System.out.println("Cliente Registado com sucesso... ");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    /**
     * Limpa os JTexfields de todo o programa...
     */
    public void limparCampos(){
        txtAlerta.setText("");
        txtCompra.setText("");
        txtDescricao.setText("");
        txtQuantidade.setText("");
        txtReferencia.setText("");
        txtVenda.setText("");
        
        txtContactoAltCli.setText("");
        txtContactoPrinCli.setText("");
        txtEmailCli.setText("");
        txtLocalizacaoCli.setText("");
        txtNomeCli.setText("");
        txtUltimaEncCli.setText("");
        txtTotalComprasCli.setText("");
        txtPesquisarCliente.setText("");
        
        txtHoraEntrega.setText("");
        txtObservacaoEnc.setText("");
        txtTotalEnc.setText("");
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    // minhas variaveis
    CategoriaJpaController catJpa = new CategoriaJpaController(Persistence.createEntityManagerFactory("projectoPU"));
    ProdutoJpaController prodJpa  = new ProdutoJpaController(Persistence.createEntityManagerFactory("projectoPU"));
    ClienteJpaController clienteJpa  = new ClienteJpaController(Persistence.createEntityManagerFactory("projectoPU"));
    UsuarioJpaController userJpa  = new UsuarioJpaController(Persistence.createEntityManagerFactory("projectoPU"));
    EncomendaJpaController encJpa  = new EncomendaJpaController(Persistence.createEntityManagerFactory("projectoPU"));
    
    List<Categoria> lista = catJpa.findCategoriaEntities();
    
    // Variaveis usadas na edicao
    Produto p = null;
    Encomenda enc = null;
    Cliente cliente = null;
    Usuario user = null;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActividades;
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEditarEncomenda;
    private javax.swing.JButton btnEditarProd;
    private javax.swing.JButton btnEditarUser;
    private javax.swing.JButton btnEncomendas;
    private javax.swing.JButton btnPesquiarCliente;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRemoverCliente;
    private javax.swing.JButton btnRemoverEncomenda;
    private javax.swing.JButton btnRemoverProdutos;
    private javax.swing.JButton btnRemoverUsuario;
    private javax.swing.JButton btnSalvarCli;
    private javax.swing.JButton btnSalvarCompra1;
    private javax.swing.JButton btnSalvarEncomenda;
    private javax.swing.JButton btnSalvarProdutos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel cartao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel pnCliente;
    private javax.swing.JPanel pnEncomenda;
    private javax.swing.JPanel pnNavegador;
    private javax.swing.JPanel pnProduto;
    private javax.swing.JPanel pnUsuario;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtAlerta;
    private com.toedter.calendar.JDateChooser txtAnoContratacao;
    private javax.swing.JComboBox<String> txtCargoUser;
    private javax.swing.JComboBox<Object> txtCategorias;
    private javax.swing.JComboBox<Object> txtClienteEnc;
    private javax.swing.JTextField txtCompra;
    private javax.swing.JTextField txtContactoAltCli;
    private javax.swing.JTextField txtContactoAlternaticoUser;
    private javax.swing.JTextField txtContactoPrinCli;
    private javax.swing.JTextField txtContactoUser;
    private javax.swing.JTextField txtDescricao;
    private com.toedter.calendar.JDateChooser txtDiaEntrega;
    private javax.swing.JTextField txtEmailCli;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JComboBox<String> txtEstadoEntrega;
    private javax.swing.JComboBox<String> txtGeneroCli;
    private javax.swing.JComboBox<String> txtGeneroUser;
    private javax.swing.JTextField txtHoraEntrega;
    private javax.swing.JTextField txtLocalizacaoCli;
    private javax.swing.JComboBox<String> txtMoradaUser;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtNomeUser;
    private javax.swing.JTextField txtObservacaoEnc;
    private javax.swing.JTextField txtPesquisarCliente;
    private javax.swing.JComboBox<Object> txtProdutoEnc;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtTotalComprasCli;
    private javax.swing.JTextField txtTotalEnc;
    private javax.swing.JTextField txtUltimaEncCli;
    private javax.swing.JTextField txtValorEntradaEnc;
    private javax.swing.JTextField txtVenda;
    // End of variables declaration//GEN-END:variables
}
